name: Build application for MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix: 
        platform: [macos-latest]
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Packages
      run: |
          pip freeze > requirements.txt
          pip install -r requirements.txt
          pip install Cython
    - name: Build Code
      run: |
          mkdir build
          cython main.py --embed
          echo "Installing Apple Developer Tools"
          xcode-select --install
          gcc main.c -o build/main.out -i cpython/Include
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifact-macos
        path: ./build
        if-no-files-found: error
    