name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix: 
        platform: [windows-latest]
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Packages
      run: |
          pip freeze > requirements.txt
          pip install -r requirements.txt
          pip install Cython
    - name: Build Code
      run: |
          mkdir build
          cython main.py --embed
          gcc main.c -o build/main.exe
    