name: Build application for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix: 
        platform: [windows-latest]
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Cython
      run: |
          pip freeze > requirements.txt
          pip install -r requirements.txt
          pip install Cython
    - name: Install Cpython for Python C API
      run: |
          echo "Cloning the cpython repo"
          git clone https://github.com/python/cpython.git
    - name: Build Code
      run: |
          echo "Creating the build dir"
          mkdir build
          python Scripts/make_win32.py
      # echo "Using cython to convert Python program to C Program"
      # cython main.py --embed
      # echo "Build main.c using gcc"
      # gcc main.c -o build/main.exe -Icpython/Include -Icpython/PC
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifact-win32
        path: ./build
        if-no-files-found: error
    
