name: Build application

on:
  push:
    brances: [ main ]
  pull_request:
    brances: [ main ]

jobs:
  build:
    strategy:
      matrix: 
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Packages
      run: |
          pip freeze > requirements.txt
          pip install -r requirements.txt
          venv .
          pip install pyinstaller
    - name: Build Code
      run: |
          pyinstaller --onefile main.py
    