name: Build application for Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix: 
        platform: [ubuntu-latest]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Packages
      run: |
          pip freeze > requirements.txt
          pip install -r requirements.txt
          pip install Cython
    - name: Install Cpython for Python C API
      run: |
          echo "Cloning the cpython repo"
          git clone https://github.com/python/cpython.git
    - name: Build Code
      run: |
          echo "Creating Build dir"
          mkdir build
          echo "Using Cython to convert Python program to C program"
          cython main.py --embed
          echo "Compile main.c using gcc"
          gcc main.c -o build/main -Icpython/Include -Icpython/PC
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifact-macos
        path: ./build
        if-no-files-found: error
    
