name: Upload Build Artifact

on:
  push: 
    branches: [ main ]

jobs:
  upload:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Packages
      run: |
        python -m pip freeze > requirements.txt
        python -m pip install -r requirements.txt

    - name: Run Build Using PyInstaller
      run: |
        python -m pyinstaller main.py

    - uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: ./dist
        if-no-files-found: warn